# baseURL = "https://keptn.sh/"
languageCode = "en-us"
title = "keptn | Opinionated framework for event-driven automated continuous operations"
theme = "hugo-serif-theme"
relativeUrls = true


[params]
    google_analytics_id="UA-133584243-1"

[blackfriday]
	plainIDAnchors = true
    # See https://github.com/gohugoio/hugo/issues/2424
	hrefTargetBlank = false
    angledQuotes = false
    latexDashes = true
    extensions = [""]
